[package]
name = "stealing-queue"
version = "0.1.0"
authors = ["Fedor Sakharov <fedor.sakharov@gmail.com>"]

[dependencies]
log = {version = "0.4", features = ["max_level_debug", "release_max_level_debug"]}
